# Generated by Django 5.2.1 on 2025-08-02 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_counter_split_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterentry',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
