# Generated by Django 5.2.1 on 2025-08-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_alter_counterentry_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='split_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('nosplit', 'NoSplit')], default='daily', max_length=10),
        ),
    ]
