# Generated by Django 5.2.9 on 2026-01-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0004_delete_pushsubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailynote',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Daily Note', 'verbose_name_plural': 'Daily Notes'},
        ),
        migrations.AlterUniqueTogether(
            name='dailynote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailynote',
            name='note_type',
            field=models.CharField(choices=[('ask_to_doctor', 'Ask to Doctor'), ('note', 'Note'), ('only_me_note', 'Only Me Note')], default='note', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailynote',
            name='note',
            field=models.CharField(max_length=255),
        ),
    ]
