# Generated by Django 5.2.1 on 2025-08-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Europe/Istanbul', max_length=50),
        ),
    ]
