services:
  db:
    image: postgres:latest
    container_name: medication-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password_medication
      POSTGRES_DB: medication
    ports:
      - "3002:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local

networks:
  my_network:
    driver: bridge
